export const admin=[
    {
        name:"Moeez",
        email:"moeez@gmail.com",
        latestSearch:"Hello",
    },
    {
        name:"Moeez",
        email:"moeez@gmail.com",
        latestSearch:"Hello",
    },
    {
        name:"Moeez",
        email:"moeez@gmail.com",
        latestSearch:"Hello",
    },
    {
        name:"Moeez",
        email:"moeez@gmail.com",
        latestSearch:"Hello",
    },
    {
        name:"Moeez",
        email:"moeez@gmail.com",
        latestSearch:"Hello",
    }
]